npmName: bandwidth-sdk
npmVersion: 1.0.0-dev
withSeparateModelsAndApi: true
modelPackage: models
apiPackage: api
gitHost: github.com
gitUserId: Bandwidth
gitRepoId: node-sdk
templateDir: custom_templates
