/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdditionalDenialReason
 */
export interface AdditionalDenialReason {
    /**
     * Reason code for denial.
     * @type {number}
     * @memberof AdditionalDenialReason
     */
    'statusCode': number;
    /**
     * Explanation for why a verification request was declined.
     * @type {string}
     * @memberof AdditionalDenialReason
     */
    'reason': string;
    /**
     * Whether a Toll-Free Verification request qualifies for resubmission via PUT.
     * @type {boolean}
     * @memberof AdditionalDenialReason
     */
    'resubmitAllowed': boolean;
}

