/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Address {
    /**
     * The name of the business using the toll-free number.
     */
    'name': string;
    /**
     * The address of the business using the toll-free number.
     */
    'addr1': string;
    /**
     * The address of the business using the toll-free number.
     */
    'addr2'?: string | null;
    /**
     * The city of the business using the toll-free number.
     */
    'city': string;
    /**
     * The state of the business using the toll-free number.
     */
    'state': string;
    /**
     * The zip of the business using the toll-free number.
     */
    'zip': string;
    /**
     * The website of the business using the toll-free number.
     */
    'url': string;
}

