/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrtcErrorSource } from './brtc-error-source';

export interface BrtcError {
    /**
     * A unique identifier for the error.
     */
    'id'?: string;
    /**
     * The type of error.
     */
    'type': string;
    /**
     * A description of the error.
     */
    'description': string;
    /**
     * A code that uniquely identifies the error.
     */
    'code'?: string;
    'source'?: BrtcErrorSource;
}

