/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The country issuing the business registration in ISO-3166-1 alpha-3 format. Alpha-2 country codes are acceptable, but the application will convert them to alpha-3 when received, so alpha-3 is encouraged.  **Note:** If this field is omitted but `businessRegistrationType` is provided, the application will attempt to infer the country based on the registration type. However, if the application cannot confidently infer the country, the submission may be rejected. To ensure the highest likelihood of acceptance, it is recommended to provide both `businessRegistrationType` and `businessRegistrationIssuingCountry`.  | Registration Type     | Supported Countries                | |----------------------|------------------------------------| | EIN                  | USA                                | | CBN                  | CAN                                | | NEQ                  | CAN                                | | PROVINCIAL_NUMBER    | CAN                                | | CRN                  | GBR, HKG                           | | VAT                  | GBR, IRL, BRA, NLD                 | | ACN                  | AUS                                | | ABN                  | AUS                                | | BRN                  | HKG                                | | SIREN                | FRA                                | | SIRET                | FRA                                | | NZBN                 | NZL                                | | UST_IDNR             | DEU                                | | CIF                  | ESP                                | | NIF                  | ESP                                | | CNPJ                 | BRA                                | | UID                  | CHE                                | | OTHER                | Must Provide Country Code          |
 */

export const BusinessRegistrationIssuingCountryEnum = {
    Usa: 'USA',
    Can: 'CAN',
    Hkg: 'HKG',
    Gbr: 'GBR',
    Irl: 'IRL',
    Bra: 'BRA',
    Nld: 'NLD',
    Aus: 'AUS',
    Fra: 'FRA',
    Nzl: 'NZL',
    Deu: 'DEU',
    Esp: 'ESP',
    Che: 'CHE',
    Cyp: 'CYP',
    Ind: 'IND',
    Chn: 'CHN',
    Bgr: 'BGR'
} as const;

export type BusinessRegistrationIssuingCountryEnum = typeof BusinessRegistrationIssuingCountryEnum[keyof typeof BusinessRegistrationIssuingCountryEnum];



