/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of registered business. If no option is applicable, please provide \"SOLE_PROPRIETOR\" as a value. Optional until early 2026; required if `businessRegistrationNumber` is provided. Available starting October 1st, 2025.
 */

export const BusinessEntityTypeEnum = {
    SoleProprietor: 'SOLE_PROPRIETOR',
    PrivateProfit: 'PRIVATE_PROFIT',
    PublicProfit: 'PUBLIC_PROFIT',
    NonProfit: 'NON_PROFIT',
    Government: 'GOVERNMENT'
} as const;

export type BusinessEntityTypeEnum = typeof BusinessEntityTypeEnum[keyof typeof BusinessEntityTypeEnum];



