/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The country issuing the business registration in ISO-3166-1 alpha-3 format.  | Registration Type     | Supported Countries                | |----------------------|------------------------------------| | EIN                  | USA                                | | CBN                  | CAN                                | | NEQ                  | CAN                                | | PROVINCIAL_NUMBER    | CAN                                | | CRN                  | GBR, HKG                           | | VAT                  | GBR, IRL, BRA, NLD                 | | ACN                  | AUS                                | | ABN                  | AUS                                | | BRN                  | HKG                                | | SIREN                | FRA                                | | SIRET                | FRA                                | | NZBN                 | NZL                                | | UST_IDNR             | DEU                                | | CIF                  | ESP                                | | NIF                  | ESP                                | | CNPJ                 | BRA                                | | UID                  | CHE                                | | OTHER                | Must Provide Country Code          |
 */

export const BusinessRegistrationIssuingCountryEnum = {
    Usa: 'USA',
    Can: 'CAN',
    Hkg: 'HKG',
    Gbr: 'GBR',
    Irl: 'IRL',
    Bra: 'BRA',
    Nld: 'NLD',
    Aus: 'AUS',
    Fra: 'FRA',
    Nzl: 'NZL',
    Deu: 'DEU',
    Esp: 'ESP',
    Che: 'CHE'
} as const;

export type BusinessRegistrationIssuingCountryEnum = typeof BusinessRegistrationIssuingCountryEnum[keyof typeof BusinessRegistrationIssuingCountryEnum];



