/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of business registration number.
 */

export const BusinessRegistrationTypeEnum = {
    Ein: 'EIN',
    Cbn: 'CBN',
    Neq: 'NEQ',
    ProvincialNumber: 'PROVINCIAL_NUMBER',
    Crn: 'CRN',
    Vat: 'VAT',
    Acn: 'ACN',
    Abn: 'ABN',
    Brn: 'BRN',
    Siren: 'SIREN',
    Siret: 'SIRET',
    Nzbn: 'NZBN',
    UstIdnr: 'UST_IDNR',
    Cif: 'CIF',
    Nif: 'NIF',
    Cnpj: 'CNPJ',
    Uid: 'UID',
    Other: 'OTHER'
} as const;

export type BusinessRegistrationTypeEnum = typeof BusinessRegistrationTypeEnum[keyof typeof BusinessRegistrationTypeEnum];



