/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The HTTP method to use to deliver the callback. GET or POST. Default value is POST.
 * @export
 * @enum {string}
 */

export const CallbackMethodEnum = {
    Get: 'GET',
    Post: 'POST'
} as const;

export type CallbackMethodEnum = typeof CallbackMethodEnum[keyof typeof CallbackMethodEnum];



