/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallTranscription } from './call-transcription';

export interface CallTranscriptionResponse {
    /**
     * The user account associated with the call.
     */
    'accountId'?: string;
    /**
     * The call id associated with the event.
     */
    'callId'?: string;
    /**
     * The programmable voice API transcription ID.
     */
    'transcriptionId'?: string;
    'tracks'?: Array<CallTranscription>;
}

