/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates the type of the callback: - `message-received` for inbound callbacks. - One of `message-sending`, `message-delivered`, `message-failed` for status callbacks. 
 * @export
 * @enum {string}
 */

export const CallbackTypeEnum = {
    Received: 'message-received',
    Sending: 'message-sending',
    Delivered: 'message-delivered',
    Failed: 'message-failed'
} as const;

export type CallbackTypeEnum = typeof CallbackTypeEnum[keyof typeof CallbackTypeEnum];



