/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CallTranscription
 */
export interface CallTranscription {
    /**
     * The detected language for this transcription.
     * @type {string}
     * @memberof CallTranscription
     */
    'detectedLanguage'?: CallTranscriptionDetectedLanguageEnum;
    /**
     * Which `track` this transcription is derived from.
     * @type {string}
     * @memberof CallTranscription
     */
    'track'?: CallTranscriptionTrackEnum;
    /**
     * The transcription itself.
     * @type {string}
     * @memberof CallTranscription
     */
    'transcript'?: string;
    /**
     * How confident the transcription engine was in transcribing the associated audio (from `0` to `1`).
     * @type {number}
     * @memberof CallTranscription
     */
    'confidence'?: number;
}

export const CallTranscriptionDetectedLanguageEnum = {
    EnUs: 'en-US',
    EsUs: 'es-US',
    FrFr: 'fr-FR'
} as const;

export type CallTranscriptionDetectedLanguageEnum = typeof CallTranscriptionDetectedLanguageEnum[keyof typeof CallTranscriptionDetectedLanguageEnum];
export const CallTranscriptionTrackEnum = {
    Inbound: 'inbound',
    Outbound: 'outbound'
} as const;

export type CallTranscriptionTrackEnum = typeof CallTranscriptionTrackEnum[keyof typeof CallTranscriptionTrackEnum];


