/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallbackMethodEnum } from './callback-method-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { ConferenceMember } from './conference-member';

export interface Conference {
    /**
     * The Bandwidth-generated conference ID.
     */
    'id'?: string;
    /**
     * The name of the conference, as specified by your application.
     */
    'name'?: string;
    /**
     * The time the conference was initiated, in ISO 8601 format.
     */
    'createdTime'?: string;
    /**
     * The time the conference was terminated, in ISO 8601 format.
     */
    'completedTime'?: string | null;
    /**
     * The URL to send the conference-related events.
     */
    'conferenceEventUrl'?: string | null;
    'conferenceEventMethod'?: CallbackMethodEnum | null;
    /**
     * The custom string attached to the conference that will be sent with callbacks.
     */
    'tag'?: string | null;
    /**
     * A list of active members of the conference. Omitted if this is a response to the [Get Conferences endpoint](/apis/voice#tag/Conferences/operation/listConferences).
     */
    'activeMembers'?: Array<ConferenceMember> | null;
}



