/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Conference Member Join event is fired whenever a caller joins a conference that specified a callbackUrl. The response may be either empty or a BXML document. Only the following verbs are valid for conferences: PlayAudio, SpeakSentence, StartRecording, StopRecording, PauseRecording, ResumeRecording. Audio verbs will be heard by all members of the conference. Recordings capture audio from all members who are not muted or on hold, as well as any audio verbs that are played into the conference.
 * @export
 * @interface ConferenceMemberJoinCallback
 */
export interface ConferenceMemberJoinCallback {
    /**
     * The event type, value can be one of the following: answer, bridgeComplete, bridgeTargetComplete, conferenceCreated, conferenceRedirect, conferenceMemberJoin, conferenceMemberExit, conferenceCompleted, conferenceRecordingAvailable, disconnect, dtmf, gather, initiate, machineDetectionComplete, recordingComplete, recordingAvailable, redirect, transcriptionAvailable, transferAnswer, transferComplete, transferDisconnect.
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'eventType'?: string;
    /**
     * The approximate UTC date and time when the event was generated by the Bandwidth server, in ISO 8601 format. This may not be exactly the time of event execution.
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'eventTime'?: string;
    /**
     * The unique, Bandwidth-generated ID of the conference that was recorded
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'conferenceId'?: string;
    /**
     * The user-specified name of the conference that was recorded
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'name'?: string;
    /**
     * The provided identifier of the caller. Must be a phone number in E.164 format (e.g. +15555555555).
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'from'?: string;
    /**
     * The phone number that received the call, in E.164 format (e.g. +15555555555).
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'to'?: string;
    /**
     * The call id associated with the event.
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'callId'?: string;
    /**
     * (optional) The tag specified on call creation. If no tag was specified or it was previously cleared, this field will not be present.
     * @type {string}
     * @memberof ConferenceMemberJoinCallback
     */
    'tag'?: string | null;
}

