/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConferenceMember
 */
export interface ConferenceMember {
    /**
     * The call id associated with the event.
     * @type {string}
     * @memberof ConferenceMember
     */
    'callId'?: string;
    /**
     * The unique, Bandwidth-generated ID of the conference that was recorded
     * @type {string}
     * @memberof ConferenceMember
     */
    'conferenceId'?: string;
    /**
     * A URL that may be used to retrieve information about or update the state of this conference member. This is the URL of this member\'s [Get Conference Member](/apis/voice/#operation/getConferenceMember) endpoint and [Modify Conference Member](/apis/voice/#operation/updateConferenceMember) endpoint.
     * @type {string}
     * @memberof ConferenceMember
     */
    'memberUrl'?: string;
    /**
     * Whether or not this member is currently muted. Members who are muted are still able to hear other participants.  If used in a PUT request, updates this member\'s mute status. Has no effect if omitted.
     * @type {boolean}
     * @memberof ConferenceMember
     */
    'mute'?: boolean;
    /**
     * Whether or not this member is currently on hold. Members who are on hold are not able to hear or speak in the conference.  If used in a PUT request, updates this member\'s hold status. Has no effect if omitted.
     * @type {boolean}
     * @memberof ConferenceMember
     */
    'hold'?: boolean;
    /**
     * If this member had a value set for `callIdsToCoach` in its [Conference](/docs/voice/bxml/conference) verb or this list was added with a previous PUT request to modify the member, this is that list of calls.  If present in a PUT request, modifies the calls that this member is coaching. Has no effect if omitted. See the documentation for the [Conference](/docs/voice/bxml/conference) verb for more details about coaching. Note that this will not add the matching calls to the conference; each call must individually execute a Conference verb to join.
     * @type {Array<string>}
     * @memberof ConferenceMember
     */
    'callIdsToCoach'?: Array<string> | null;
}

