/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Contact {
    /**
     * The first name of the business contact using the toll-free number.
     */
    'firstName': string;
    /**
     * The last name of the business contact using the toll-free number.
     */
    'lastName': string;
    'email': string;
    /**
     * Contact telephone number
     */
    'phoneNumber': string;
}

