/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FieldError } from './field-error';

/**
 * 
 * @export
 * @interface CreateMessageRequestError
 */
export interface CreateMessageRequestError {
    /**
     * 
     * @type {string}
     * @memberof CreateMessageRequestError
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof CreateMessageRequestError
     */
    'description': string;
    /**
     * 
     * @type {Array<FieldError>}
     * @memberof CreateMessageRequestError
     */
    'fieldErrors'?: Array<FieldError>;
}

