/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorObject } from './error-object';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageData } from './multi-channel-message-data';

/**
 * 
 * @export
 * @interface CreateMultiChannelMessageResponse
 */
export interface CreateMultiChannelMessageResponse {
    /**
     * 
     * @type {Array<Link>}
     * @memberof CreateMultiChannelMessageResponse
     */
    'links'?: Array<Link>;
    /**
     * 
     * @type {MultiChannelMessageData}
     * @memberof CreateMultiChannelMessageResponse
     */
    'data'?: MultiChannelMessageData;
    /**
     * 
     * @type {Array<ErrorObject>}
     * @memberof CreateMultiChannelMessageResponse
     */
    'errors'?: Array<ErrorObject>;
}

