/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorObject } from './error-object';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageResponseData } from './multi-channel-message-response-data';

export interface CreateMultiChannelMessageResponse {
    'links'?: Array<Link>;
    'data'?: MultiChannelMessageResponseData;
    'errors'?: Array<ErrorObject>;
}

