/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Diversion {
    /**
     * The reason for the diversion. Common values: unknown, user-busy, no-answer, unavailable, unconditional, time-of-day, do-not-disturb, deflection, follow-me, out-of-service, away.
     */
    'reason'?: string;
    /**
     * off or full
     */
    'privacy'?: string;
    /**
     * No if the number was provided by the user, yes if the number was provided by the network
     */
    'screen'?: string;
    /**
     * The number of diversions that have occurred
     */
    'counter'?: string;
    /**
     * The maximum number of diversions allowed for this session
     */
    'limit'?: string;
    /**
     * The normal list of values is not exhaustive. Your application must be tolerant of unlisted keys and unlisted values of those keys.
     */
    'unknown'?: string;
    /**
     * Always present. Indicates the last telephone number that the call was diverted from.
     */
    'origTo'?: string;
}

