/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specifies relevant sources of the error, if any.
 */
export interface ErrorSource {
    /**
     * The relevant URI query parameter causing the error
     */
    'parameter'?: string;
    /**
     * The request body field that led to the error
     */
    'field'?: string;
    /**
     * The header field that contributed to the error
     */
    'header'?: string;
    /**
     * A resource ID or path linked to the error
     */
    'reference'?: string;
}

