/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorSource } from './error-source';

/**
 * 
 * @export
 * @interface ErrorObject
 */
export interface ErrorObject {
    /**
     * A concise summary of the error used for categorization.
     * @type {string}
     * @memberof ErrorObject
     */
    'type': string;
    /**
     * A detailed explanation of the error.
     * @type {string}
     * @memberof ErrorObject
     */
    'description': string;
    /**
     * 
     * @type {ErrorSource}
     * @memberof ErrorObject
     */
    'source': ErrorSource;
}

