/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FieldError
 */
export interface FieldError {
    /**
     * The name of the field that contains the error
     * @type {string}
     * @memberof FieldError
     */
    'fieldName'?: string;
    /**
     * The error associated with the field
     * @type {string}
     * @memberof FieldError
     */
    'description'?: string;
}

