/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The format that the recording is stored in.
 */

export const FileFormatEnum = {
    Mp3: 'mp3',
    Wav: 'wav'
} as const;

export type FileFormatEnum = typeof FileFormatEnum[keyof typeof FileFormatEnum];



