/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallDirectionEnum } from './call-direction-enum';

/**
 * The gather event is sent after a <Gather> verb is executed. Its purpose is to report the gathered digits to the calling application.
 */
export interface GatherCallback {
    /**
     * The event type, value can be one of the following: answer, bridgeComplete, bridgeTargetComplete, conferenceCreated, conferenceRedirect, conferenceMemberJoin, conferenceMemberExit, conferenceCompleted, conferenceRecordingAvailable, disconnect, dtmf, gather, initiate, machineDetectionComplete, recordingComplete, recordingAvailable, redirect, transcriptionAvailable, transferAnswer, transferComplete, transferDisconnect.
     */
    'eventType'?: string;
    /**
     * The approximate UTC date and time when the event was generated by the Bandwidth server, in ISO 8601 format. This may not be exactly the time of event execution.
     */
    'eventTime'?: string;
    /**
     * The user account associated with the call.
     */
    'accountId'?: string;
    /**
     * The id of the application associated with the call.
     */
    'applicationId'?: string;
    /**
     * The provided identifier of the caller. Must be a phone number in E.164 format (e.g. +15555555555).
     */
    'from'?: string;
    /**
     * The phone number that received the call, in E.164 format (e.g. +15555555555).
     */
    'to'?: string;
    'direction'?: CallDirectionEnum;
    /**
     * The call id associated with the event.
     */
    'callId'?: string;
    /**
     * (optional) The digits, letters, and/or symbols entered by the user. The string is empty if a timeout occurred before any buttons were pressed.
     */
    'digits'?: string;
    /**
     * The URL of the call associated with the event.
     */
    'callUrl'?: string;
    /**
     * (optional) If call queueing is enabled and this is an outbound call, time the call was queued, in ISO 8601 format.
     */
    'enqueuedTime'?: string | null;
    /**
     * Time the call was started, in ISO 8601 format.
     */
    'startTime'?: string;
    /**
     * Time the call was answered, in ISO 8601 format.
     */
    'answerTime'?: string | null;
    /**
     * (optional) If the event is related to the B leg of a <Transfer>, the call id of the original call leg that executed the <Transfer>. Otherwise, this field will not be present.
     */
    'parentCallId'?: string;
    /**
     * (optional) The digit the user pressed to end the gather. Empty string value if no terminating digit was pressed.
     */
    'terminatingDigit'?: string;
    /**
     * The phone number used as the from field of the B-leg call, in E.164 format (e.g. +15555555555).
     */
    'transferCallerId'?: string;
    /**
     * The phone number used as the to field of the B-leg call, in E.164 format (e.g. +15555555555).
     */
    'transferTo'?: string;
    /**
     * (optional) The tag specified on call creation. If no tag was specified or it was previously cleared, this field will not be present.
     */
    'tag'?: string | null;
}



