/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const InProgressLookupStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    PartialComplete: 'PARTIAL_COMPLETE',
    Failed: 'FAILED'
} as const;

export type InProgressLookupStatusEnum = typeof InProgressLookupStatusEnum[keyof typeof InProgressLookupStatusEnum];



