/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible inbound callback types originating from MO messages or multichannel message client responses: - `message-received` indicates an MO message from a Bandwidth user\'s client to a Bandwidth number. - `request-location-response` indicates a response to a location request sent by the Bandwidth user\'s client after receiving an RBM message.  - `suggestion-response` indicates a response to a suggestion sent by the Bandwidth user\'s client after receiving an RBM message.
 * @export
 * @enum {string}
 */

export const InboundCallbackTypeEnum = {
    MessageReceived: 'message-received',
    RequestLocationResponse: 'request-location-response',
    SuggestionResponse: 'suggestion-response'
} as const;

export type InboundCallbackTypeEnum = typeof InboundCallbackTypeEnum[keyof typeof InboundCallbackTypeEnum];



