/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageDirectionEnum } from './message-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageChannelEnum } from './multi-channel-message-channel-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageContent } from './multi-channel-message-content';
// May contain unused imports in some cases
// @ts-ignore
import type { PriorityEnum } from './priority-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmLocationResponse } from './rbm-location-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmSuggestionResponse } from './rbm-suggestion-response';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusCallbackMessage } from './status-callback-message';

/**
 * @type InboundCallbackMessage
 */
export type InboundCallbackMessage = StatusCallbackMessage;


