/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InboundMessageCallbackMessage } from './inbound-message-callback-message';

/**
 * Inbound Message Callback
 * @export
 * @interface InboundMessageCallback
 */
export interface InboundMessageCallback {
    /**
     * 
     * @type {string}
     * @memberof InboundMessageCallback
     */
    'time': string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageCallback
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageCallback
     */
    'to': string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageCallback
     */
    'description': string;
    /**
     * 
     * @type {InboundMessageCallbackMessage}
     * @memberof InboundMessageCallback
     */
    'message': InboundMessageCallbackMessage;
}

