/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface LinkSchema {
    /**
     * URI of the link.
     */
    'href'?: string;
    /**
     * Specifies the relationship between this link and the resource.
     */
    'rel'?: string;
    /**
     * HTTP method to be used.
     */
    'method'?: string;
}

