/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrtcError } from './brtc-error';
// May contain unused imports in some cases
// @ts-ignore
import type { BrtcLink } from './brtc-link';
// May contain unused imports in some cases
// @ts-ignore
import type { Endpoints } from './endpoints';
// May contain unused imports in some cases
// @ts-ignore
import type { Page } from './page';

export interface ListEndpointsResponse {
    'links': Array<BrtcLink>;
    'page'?: Page;
    'data': Array<Endpoints>;
    'errors': Array<BrtcError>;
}

