/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ListMessageDirectionEnum } from './list-message-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import { MessageStatusEnum } from './message-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import { MessageTypeEnum } from './message-type-enum';

/**
 * 
 * @export
 * @interface ListMessageItem
 */
export interface ListMessageItem {
    /**
     * The message id
     * @type {string}
     * @memberof ListMessageItem
     */
    'messageId'?: string;
    /**
     * The account id associated with this message.
     * @type {string}
     * @memberof ListMessageItem
     */
    'accountId'?: string;
    /**
     * The source phone number of the message.
     * @type {string}
     * @memberof ListMessageItem
     */
    'sourceTn'?: string;
    /**
     * The recipient phone number of the message.
     * @type {string}
     * @memberof ListMessageItem
     */
    'destinationTn'?: string;
    /**
     * 
     * @type {MessageStatusEnum}
     * @memberof ListMessageItem
     */
    'messageStatus'?: MessageStatusEnum;
    /**
     * 
     * @type {ListMessageDirectionEnum}
     * @memberof ListMessageItem
     */
    'messageDirection'?: ListMessageDirectionEnum;
    /**
     * 
     * @type {MessageTypeEnum}
     * @memberof ListMessageItem
     */
    'messageType'?: MessageTypeEnum;
    /**
     * The number of segments the message was sent as.
     * @type {number}
     * @memberof ListMessageItem
     */
    'segmentCount'?: number;
    /**
     * The numeric error code of the message.
     * @type {number}
     * @memberof ListMessageItem
     */
    'errorCode'?: number;
    /**
     * The ISO 8601 datetime of the message.
     * @type {string}
     * @memberof ListMessageItem
     */
    'receiveTime'?: string;
    /**
     * The name of the carrier. Not currently supported for MMS coming soon.
     * @type {string}
     * @memberof ListMessageItem
     */
    'carrierName'?: string | null;
    /**
     * The size of the message including message content and headers.
     * @type {number}
     * @memberof ListMessageItem
     */
    'messageSize'?: number | null;
    /**
     * The length of the message content.
     * @type {number}
     * @memberof ListMessageItem
     */
    'messageLength'?: number;
    /**
     * The number of attachments the message has.
     * @type {number}
     * @memberof ListMessageItem
     */
    'attachmentCount'?: number | null;
    /**
     * The number of recipients the message has.
     * @type {number}
     * @memberof ListMessageItem
     */
    'recipientCount'?: number | null;
    /**
     * The campaign class of the message if it has one.
     * @type {string}
     * @memberof ListMessageItem
     */
    'campaignClass'?: string | null;
    /**
     * The campaign ID of the message if it has one.
     * @type {string}
     * @memberof ListMessageItem
     */
    'campaignId'?: string | null;
}



