/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LookupErrorSchemaMeta } from './lookup-error-schema-meta';

export interface LookupErrorSchema {
    /**
     * Validation error code
     */
    'code'?: string;
    /**
     * Description of validation error
     */
    'description'?: string;
    /**
     * Type of validation error
     */
    'type'?: string;
    'meta'?: LookupErrorSchemaMeta;
}

