/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Create phone number lookup request.
 * @export
 * @interface LookupRequest
 */
export interface LookupRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof LookupRequest
     */
    'tns': Array<string>;
}

