/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LinkSchema } from './link-schema';
// May contain unused imports in some cases
// @ts-ignore
import type { LookupErrorSchema } from './lookup-error-schema';

/**
 * 
 * @export
 * @interface LookupErrorResponse
 */
export interface LookupErrorResponse {
    /**
     * 
     * @type {Array<LinkSchema>}
     * @memberof LookupErrorResponse
     */
    'links'?: Array<LinkSchema>;
    /**
     * The phone number lookup response data
     * @type {object}
     * @memberof LookupErrorResponse
     */
    'data'?: object;
    /**
     * 
     * @type {Array<LookupErrorSchema>}
     * @memberof LookupErrorResponse
     */
    'errors'?: Array<LookupErrorSchema>;
}

