/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The status of the request (IN_PROGRESS, COMPLETE, PARTIAL_COMPLETE, or FAILED).
 * @export
 * @enum {string}
 */

export const LookupStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    PartialComplete: 'PARTIAL_COMPLETE',
    Failed: 'FAILED'
} as const;

export type LookupStatusEnum = typeof LookupStatusEnum[keyof typeof LookupStatusEnum];



