/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface LookupErrorSchemaMeta {
    'phoneNumbers'?: Array<string>;
    /**
     * Message describing the error
     */
    'message'?: string;
    /**
     * Error code associated with the message
     */
    'code'?: number;
}

