/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListMessageItem } from './list-message-item';
// May contain unused imports in some cases
// @ts-ignore
import type { PageInfo } from './page-info';

export interface MessagesList {
    /**
     * The total number of messages matched by the search. When the request has limitTotalCount set to true this value is limited to 10,000.
     */
    'totalCount'?: number;
    'pageInfo'?: PageInfo;
    'messages'?: Array<ListMessageItem>;
}

