/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageDeliveredCallbackMessage } from './message-delivered-callback-message';

/**
 * Message Delivered Callback
 * @export
 * @interface MessageDeliveredCallback
 */
export interface MessageDeliveredCallback {
    /**
     * 
     * @type {string}
     * @memberof MessageDeliveredCallback
     */
    'time': string;
    /**
     * 
     * @type {string}
     * @memberof MessageDeliveredCallback
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof MessageDeliveredCallback
     */
    'to': string;
    /**
     * 
     * @type {string}
     * @memberof MessageDeliveredCallback
     */
    'description': string;
    /**
     * 
     * @type {MessageDeliveredCallbackMessage}
     * @memberof MessageDeliveredCallback
     */
    'message': MessageDeliveredCallbackMessage;
}

