/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageDirectionEnum } from './message-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { PriorityEnum } from './priority-enum';

/**
 * Message Failed Callback Message Schema
 * @export
 * @interface MessageFailedCallbackMessage
 */
export interface MessageFailedCallbackMessage {
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'owner': string;
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'applicationId': string;
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'time': string;
    /**
     * 
     * @type {number}
     * @memberof MessageFailedCallbackMessage
     */
    'segmentCount': number;
    /**
     * 
     * @type {MessageDirectionEnum}
     * @memberof MessageFailedCallbackMessage
     */
    'direction': MessageDirectionEnum;
    /**
     * 
     * @type {Set<string>}
     * @memberof MessageFailedCallbackMessage
     */
    'to': Set<string>;
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'from': string;
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof MessageFailedCallbackMessage
     */
    'tag': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageFailedCallbackMessage
     */
    'media'?: Array<string>;
    /**
     * 
     * @type {PriorityEnum}
     * @memberof MessageFailedCallbackMessage
     */
    'priority'?: PriorityEnum;
}



