/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessagingCodeResponse
 */
export interface MessagingCodeResponse {
    /**
     * Messaging API Message ID.
     * @type {string}
     * @memberof MessagingCodeResponse
     */
    'messageId'?: string;
}

