/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MmsMessageContentFile } from './mms-message-content-file';

export interface MmsMessageContent {
    /**
     * The contents of the text message. Must be 2048 characters or less.
     */
    'text'?: string;
    'media'?: Array<MmsMessageContentFile>;
}

