/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The channel of the multi-channel message.
 * @export
 * @enum {string}
 */

export const MultiChannelMessageChannelEnum = {
    Rbm: 'RBM',
    Sms: 'SMS',
    Mms: 'MMS'
} as const;

export type MultiChannelMessageChannelEnum = typeof MultiChannelMessageChannelEnum[keyof typeof MultiChannelMessageChannelEnum];



