/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CardWidthEnum } from './card-width-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelAction } from './multi-channel-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmCardContent } from './rbm-card-content';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmMessageContentFile } from './rbm-message-content-file';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmMessageContentRichCard } from './rbm-message-content-rich-card';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmMessageContentText } from './rbm-message-content-text';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmMessageMedia } from './rbm-message-media';
// May contain unused imports in some cases
// @ts-ignore
import type { StandaloneCardOrientationEnum } from './standalone-card-orientation-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { ThumbnailAlignmentEnum } from './thumbnail-alignment-enum';

/**
 * @type MultiChannelChannelListRBMObjectAllOfContent
 * The content of the message.
 */
export type MultiChannelChannelListRBMObjectAllOfContent = RbmMessageContentRichCard | RbmMessageContentText | RbmMessageMedia;


