/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MmsMessageContent } from './mms-message-content';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListMMSObject } from './multi-channel-channel-list-mmsobject';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListRBMObject } from './multi-channel-channel-list-rbmobject';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListSMSObject } from './multi-channel-channel-list-smsobject';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageChannelEnum } from './multi-channel-message-channel-enum';

export interface MultiChannelChannelListRequestObject {
    /**
     * The sender ID of the message. This could be an alphanumeric sender ID.
     */
    'from': string;
    /**
     * The ID of the Application your from number or senderId is associated with in the Bandwidth Phone Number Dashboard.
     */
    'applicationId': string;
    'channel': MultiChannelMessageChannelEnum;
    'content': MmsMessageContent;
}



