/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MmsMessageContent } from './mms-message-content';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListMMSResponseObject } from './multi-channel-channel-list-mmsresponse-object';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListRBMResponseObject } from './multi-channel-channel-list-rbmresponse-object';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListSMSResponseObject } from './multi-channel-channel-list-smsresponse-object';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageChannelEnum } from './multi-channel-message-channel-enum';

/**
 * 
 * @export
 * @interface MultiChannelChannelListResponseObject
 */
export interface MultiChannelChannelListResponseObject {
    /**
     * The sender ID of the message. This could be an alphanumeric sender ID.
     * @type {string}
     * @memberof MultiChannelChannelListResponseObject
     */
    'from': string;
    /**
     * The ID of the Application your from number or senderId is associated with in the Bandwidth Phone Number Dashboard.
     * @type {string}
     * @memberof MultiChannelChannelListResponseObject
     */
    'applicationId': string;
    /**
     * 
     * @type {MultiChannelMessageChannelEnum}
     * @memberof MultiChannelChannelListResponseObject
     */
    'channel': MultiChannelMessageChannelEnum;
    /**
     * 
     * @type {MmsMessageContent}
     * @memberof MultiChannelChannelListResponseObject
     */
    'content': MmsMessageContent;
    /**
     * The Bandwidth senderId associated with the message. Identical to \'from\'.
     * @type {string}
     * @memberof MultiChannelChannelListResponseObject
     */
    'owner': string;
}



