/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelActionCalendarEvent } from './multi-channel-action-calendar-event';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionBase } from './rbm-action-base';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionDial } from './rbm-action-dial';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionOpenUrl } from './rbm-action-open-url';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionTypeEnum } from './rbm-action-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionViewLocation } from './rbm-action-view-location';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmOpenUrlEnum } from './rbm-open-url-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmWebViewEnum } from './rbm-web-view-enum';

export interface MultiChannelAction {
    'type': RbmActionTypeEnum;
    /**
     * Displayed text for user to click
     */
    'text': string;
    /**
     * Base64 payload the customer receives when the reply is clicked.
     */
    'postbackData': string;
    /**
     * The phone number to dial. Must be E164 format.
     */
    'phoneNumber': string;
    /**
     * The latitude of the location. Must be in range [-90.000000, 90.000000].
     */
    'latitude': number;
    /**
     * The longitude of the location. Must be in range [-180.000000, 180.000000].
     */
    'longitude': number;
    /**
     * The label of the location.
     */
    'label'?: string;
    /**
     * The title of the event.
     */
    'title': string;
    /**
     * The start time of the event. Must be a valid RFC-3339 value, e.g., 2021-03-14T01:59:26Z or 2021-03-13T20:59:26-05:00.
     */
    'startTime': string;
    /**
     * The end time of the event. Must be a valid RFC-3339 value, e.g., 2021-03-14T01:59:26Z or 2021-03-13T20:59:26-05:00.
     */
    'endTime': string;
    /**
     * The description of the event.
     */
    'description'?: string;
    /**
     * The URL to open in browser. Must use http:// or https:// scheme.
     */
    'url': string;
    'application'?: RbmOpenUrlEnum;
    'webviewViewMode'?: RbmWebViewEnum;
}



