/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageCallbackData } from './multi-channel-message-callback-data';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelStatusEnum } from './multi-channel-status-enum';

/**
 * 
 * @export
 * @interface MultiChannelCallbackData
 */
export interface MultiChannelCallbackData {
    /**
     * The time of the callback event.
     * @type {string}
     * @memberof MultiChannelCallbackData
     */
    'time'?: string;
    /**
     * 
     * @type {MultiChannelStatusEnum}
     * @memberof MultiChannelCallbackData
     */
    'type'?: MultiChannelStatusEnum;
    /**
     * The phone number the message should be sent to in E164 format.
     * @type {string}
     * @memberof MultiChannelCallbackData
     */
    'to'?: string;
    /**
     * 
     * @type {string}
     * @memberof MultiChannelCallbackData
     */
    'description'?: string;
    /**
     * 
     * @type {MultiChannelMessageCallbackData}
     * @memberof MultiChannelCallbackData
     */
    'message'?: MultiChannelMessageCallbackData;
}



