/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageChannelEnum } from './multi-channel-message-channel-enum';

/**
 * 
 * @export
 * @interface MultiChannelChannelListObjectBase
 */
export interface MultiChannelChannelListObjectBase {
    /**
     * The sender ID of the message. This could be an alphanumeric sender ID.
     * @type {string}
     * @memberof MultiChannelChannelListObjectBase
     */
    'from': string;
    /**
     * The ID of the Application your from number or senderId is associated with in the Bandwidth Phone Number Dashboard.
     * @type {string}
     * @memberof MultiChannelChannelListObjectBase
     */
    'applicationId': string;
    /**
     * 
     * @type {MultiChannelMessageChannelEnum}
     * @memberof MultiChannelChannelListObjectBase
     */
    'channel': MultiChannelMessageChannelEnum;
}



