/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelChannelListRequestObject } from './multi-channel-channel-list-request-object';
// May contain unused imports in some cases
// @ts-ignore
import type { PriorityEnum } from './priority-enum';

/**
 * Multi-Channel Message Request
 * @export
 * @interface MultiChannelMessageRequest
 */
export interface MultiChannelMessageRequest {
    /**
     * The phone number the message should be sent to in E164 format.
     * @type {string}
     * @memberof MultiChannelMessageRequest
     */
    'to': string;
    /**
     * A list of message bodies. The messages will be attempted in the order they are listed. Once a message sends successfully, the others will be ignored.
     * @type {Array<MultiChannelChannelListRequestObject>}
     * @memberof MultiChannelMessageRequest
     */
    'channelList': Array<MultiChannelChannelListRequestObject>;
    /**
     * A custom string that will be included in callback events of the message. Max 1024 characters.
     * @type {string}
     * @memberof MultiChannelMessageRequest
     */
    'tag'?: string;
    /**
     * 
     * @type {PriorityEnum}
     * @memberof MultiChannelMessageRequest
     */
    'priority'?: PriorityEnum;
    /**
     * A string with the date/time value that the message will automatically expire by. This must be a valid RFC-3339 value, e.g., 2021-03-14T01:59:26Z or 2021-03-13T20:59:26-05:00. Must be a date-time in the future.
     * @type {string}
     * @memberof MultiChannelMessageRequest
     */
    'expiration'?: string;
}



