/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     * The link to the previous page for pagination.
     * @type {string}
     * @memberof PageInfo
     */
    'prevPage'?: string;
    /**
     * The link to the next page for pagination.
     * @type {string}
     * @memberof PageInfo
     */
    'nextPage'?: string;
    /**
     * The isolated pagination token for the previous page.
     * @type {string}
     * @memberof PageInfo
     */
    'prevPageToken'?: string;
    /**
     * The isolated pagination token for the next page.
     * @type {string}
     * @memberof PageInfo
     */
    'nextPageToken'?: string;
}

