/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specifies the message\'s sending priority with respect to other messages in your account. For best results and optimal throughput, reserve the \'high\' priority setting for critical messages only.
 * @export
 * @enum {string}
 */

export const PriorityEnum = {
    Default: 'default',
    High: 'high'
} as const;

export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];



