/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of product associated with the message.
 * @export
 * @enum {string}
 */

export const ProductTypeEnum = {
    LocalA2P: 'LOCAL_A2P',
    P2P: 'P2P',
    ShortCodeReach: 'SHORT_CODE_REACH',
    TollFree: 'TOLL_FREE',
    HostedShortCode: 'HOSTED_SHORT_CODE',
    AlphaNumeric: 'ALPHA_NUMERIC',
    RbmMedia: 'RBM_MEDIA',
    RbmRich: 'RBM_RICH',
    RbmConversational: 'RBM_CONVERSATIONAL'
} as const;

export type ProductTypeEnum = typeof ProductTypeEnum[keyof typeof ProductTypeEnum];



