/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The height of the media.
 */

export const RbmMediaHeightEnum = {
    Short: 'SHORT',
    Medium: 'MEDIUM',
    Tall: 'TALL'
} as const;

export type RbmMediaHeightEnum = typeof RbmMediaHeightEnum[keyof typeof RbmMediaHeightEnum];



