/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RbmSuggestionResponse {
    /**
     * The text associated with the suggestion response.
     */
    'text'?: string;
    /**
     * Base64 payload the customer receives when the reply is clicked.
     */
    'postbackData'?: string;
}

