/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RbmMessageContentFile {
    /**
     * The URL of the media file. 100MB is the maximum file size.
     */
    'fileUrl': string;
    /**
     * The URL of the thumbnail image. Applies only to video file media.
     */
    'thumbnailUrl'?: string;
}

