/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const RbmActionTypeEnum = {
    Reply: 'REPLY',
    DialPhone: 'DIAL_PHONE',
    ShowLocation: 'SHOW_LOCATION',
    CreateCalendarEvent: 'CREATE_CALENDAR_EVENT',
    OpenUrl: 'OPEN_URL',
    RequestLocation: 'REQUEST_LOCATION'
} as const;

export type RbmActionTypeEnum = typeof RbmActionTypeEnum[keyof typeof RbmActionTypeEnum];



