/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RbmLocationResponse
 */
export interface RbmLocationResponse {
    /**
     * The latitude of the client\'s location.
     * @type {number}
     * @memberof RbmLocationResponse
     */
    'latitude'?: number;
    /**
     * The longitude of the client\'s location.
     * @type {number}
     * @memberof RbmLocationResponse
     */
    'longitude'?: number;
}

