/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RbmMediaHeightEnum } from './rbm-media-height-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmMessageContentFile } from './rbm-message-content-file';

/**
 * 
 * @export
 * @interface RbmCardContentMedia
 */
export interface RbmCardContentMedia {
    /**
     * 
     * @type {RbmMediaHeightEnum}
     * @memberof RbmCardContentMedia
     */
    'height': RbmMediaHeightEnum;
    /**
     * 
     * @type {RbmMessageContentFile}
     * @memberof RbmCardContentMedia
     */
    'file': RbmMessageContentFile;
}



