/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelAction } from './multi-channel-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmCardContentMedia } from './rbm-card-content-media';

export interface RbmCardContent {
    /**
     * The title of the card. Must be 200 characters or less.
     */
    'title'?: string;
    /**
     * The description of the card. Must be 2000 characters or less.
     */
    'description'?: string;
    'media'?: RbmCardContentMedia;
    /**
     * An array of suggested actions for the recipient that will be displayed on the rich card.
     */
    'suggestions'?: Array<MultiChannelAction>;
}

