/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionBase } from './rbm-action-base';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionTypeEnum } from './rbm-action-type-enum';

/**
 * @type RbmActionDial
 */
export type RbmActionDial = {
    'type': RbmActionTypeEnum;
    /**
     * Displayed text for user to click
     */
    'text': string;
    /**
     * Base64 payload the customer receives when the reply is clicked.
     */
    'postbackData': string;
    /**
     * The phone number to dial. Must be E164 format.
     */
    'phoneNumber': string;
};


