/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionBase } from './rbm-action-base';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmActionTypeEnum } from './rbm-action-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmOpenUrlEnum } from './rbm-open-url-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmVebViewEnum } from './rbm-veb-view-enum';

/**
 * @type RbmActionOpenUrl
 */
export type RbmActionOpenUrl = RbmActionBase;


