/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelAction } from './multi-channel-action';

/**
 * 
 * @export
 * @interface RbmMessageContentText
 */
export interface RbmMessageContentText {
    /**
     * The text associated with the message. Must be 3270 characters or less
     * @type {string}
     * @memberof RbmMessageContentText
     */
    'text': string;
    /**
     * An array of suggested actions for the recipient.
     * @type {Array<MultiChannelAction>}
     * @memberof RbmMessageContentText
     */
    'suggestions'?: Array<MultiChannelAction>;
}

