/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelAction } from './multi-channel-action';
// May contain unused imports in some cases
// @ts-ignore
import type { RbmMessageContentFile } from './rbm-message-content-file';

/**
 * 
 * @export
 * @interface RbmMessageMedia
 */
export interface RbmMessageMedia {
    /**
     * 
     * @type {RbmMessageContentFile}
     * @memberof RbmMessageMedia
     */
    'media': RbmMessageContentFile;
    /**
     * An array of suggested actions for the recipient.
     * @type {Array<MultiChannelAction>}
     * @memberof RbmMessageMedia
     */
    'suggestions'?: Array<MultiChannelAction>;
}

