/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallDirectionEnum } from './call-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { FileFormatEnum } from './file-format-enum';

/**
 * The Recording Available event is sent after a recording has been processed. It indicates that the recording is available for download.
 * @export
 * @interface RecordingAvailableCallback
 */
export interface RecordingAvailableCallback {
    /**
     * The event type, value can be one of the following: answer, bridgeComplete, bridgeTargetComplete, conferenceCreated, conferenceRedirect, conferenceMemberJoin, conferenceMemberExit, conferenceCompleted, conferenceRecordingAvailable, disconnect, dtmf, gather, initiate, machineDetectionComplete, recordingComplete, recordingAvailable, redirect, transcriptionAvailable, transferAnswer, transferComplete, transferDisconnect.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'eventType'?: string;
    /**
     * The approximate UTC date and time when the event was generated by the Bandwidth server, in ISO 8601 format. This may not be exactly the time of event execution.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'eventTime'?: string;
    /**
     * The user account associated with the call.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'accountId'?: string;
    /**
     * The id of the application associated with the call.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'applicationId'?: string;
    /**
     * The provided identifier of the caller. Must be a phone number in E.164 format (e.g. +15555555555).
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'from'?: string;
    /**
     * The phone number that received the call, in E.164 format (e.g. +15555555555).
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'to'?: string;
    /**
     * 
     * @type {CallDirectionEnum}
     * @memberof RecordingAvailableCallback
     */
    'direction'?: CallDirectionEnum;
    /**
     * The call id associated with the event.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'callId'?: string;
    /**
     * The URL of the call associated with the event.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'callUrl'?: string;
    /**
     * (optional) If the event is related to the B leg of a <Transfer>, the call id of the original call leg that executed the <Transfer>. Otherwise, this field will not be present.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'parentCallId'?: string;
    /**
     * The unique ID of this recording
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'recordingId'?: string;
    /**
     * The URL that can be used to download the recording. Only present if the recording is finished and may be downloaded.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'mediaUrl'?: string | null;
    /**
     * (optional) If call queueing is enabled and this is an outbound call, time the call was queued, in ISO 8601 format.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'enqueuedTime'?: string | null;
    /**
     * Time the call was started, in ISO 8601 format.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'startTime'?: string;
    /**
     * The time that the recording ended in ISO-8601 format
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'endTime'?: string;
    /**
     * The duration of the recording in ISO-8601 format
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'duration'?: string;
    /**
     * 
     * @type {FileFormatEnum}
     * @memberof RecordingAvailableCallback
     */
    'fileFormat'?: FileFormatEnum;
    /**
     * Always `1` for conference recordings; multi-channel recordings are not supported on conferences.
     * @type {number}
     * @memberof RecordingAvailableCallback
     */
    'channels'?: number;
    /**
     * (optional) The tag specified on call creation. If no tag was specified or it was previously cleared, this field will not be present.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'tag'?: string | null;
    /**
     * The current status of the process. For recording, current possible values are \'processing\', \'partial\', \'complete\', \'deleted\', and \'error\'. For transcriptions, current possible values are \'none\', \'processing\', \'available\', \'error\', \'timeout\', \'file-size-too-big\', and \'file-size-too-small\'. Additional states may be added in the future, so your application must be tolerant of unknown values.
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'status'?: string;
    /**
     * The phone number used as the from field of the B-leg call, in E.164 format (e.g. +15555555555).
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'transferCallerId'?: string;
    /**
     * The phone number used as the to field of the B-leg call, in E.164 format (e.g. +15555555555).
     * @type {string}
     * @memberof RecordingAvailableCallback
     */
    'transferTo'?: string;
}



