/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * If the recording was transcribed, metadata about the transcription
 */
export interface RecordingTranscriptionMetadata {
    /**
     * The unique transcription ID
     */
    'id'?: string;
    /**
     * The current status of the process. For recording, current possible values are \'processing\', \'partial\', \'complete\', \'deleted\', and \'error\'. For transcriptions, current possible values are \'none\', \'processing\', \'available\', \'error\', \'timeout\', \'file-size-too-big\', and \'file-size-too-small\'. Additional states may be added in the future, so your application must be tolerant of unknown values.
     */
    'status'?: string;
    /**
     * The time that the transcription was completed
     */
    'completedTime'?: string;
    /**
     * The URL of the [transcription](#operation/getCallTranscription)
     */
    'url'?: string;
}

