/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The HTTP method to use for the request to `redirectUrl`. GET or POST. Default value is POST.<br><br>Not allowed if `state` is `completed`.
 * @export
 * @enum {string}
 */

export const RedirectMethodEnum = {
    Get: 'GET',
    Post: 'POST'
} as const;

export type RedirectMethodEnum = typeof RedirectMethodEnum[keyof typeof RedirectMethodEnum];



