/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallDirectionEnum } from './call-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { ReferCallStatusEnum } from './refer-call-status-enum';

/**
 * This event is sent to the referCompleteUrl of a call\'s <Refer> verb when the SIP REFER flow completes. On success, the call has been torn down and the BXML returned from this callback is ignored. On failure, the call remains active and the BXML returned from this callback is executed on the call.
 */
export interface ReferCompleteCallback {
    /**
     * The event type, value can be one of the following: answer, bridgeComplete, bridgeTargetComplete, conferenceCreated, conferenceRedirect, conferenceMemberJoin, conferenceMemberExit, conferenceCompleted, conferenceRecordingAvailable, disconnect, dtmf, gather, initiate, machineDetectionComplete, recordingComplete, recordingAvailable, redirect, referComplete, transcriptionAvailable, transferAnswer, transferComplete, transferDisconnect.
     */
    'eventType'?: string;
    /**
     * The approximate UTC date and time when the event was generated by the Bandwidth server, in ISO 8601 format. This may not be exactly the time of event execution.
     */
    'eventTime'?: string;
    /**
     * The user account associated with the call.
     */
    'accountId'?: string;
    /**
     * The id of the application associated with the call.
     */
    'applicationId'?: string;
    /**
     * The provided identifier of the caller. Must be a phone number in E.164 format (e.g. +15555555555).
     */
    'from'?: string;
    /**
     * The phone number that received the call, in E.164 format (e.g. +15555555555).
     */
    'to'?: string;
    'direction'?: CallDirectionEnum;
    /**
     * The call id associated with the event.
     */
    'callId'?: string;
    /**
     * The URL of the call associated with the event.
     */
    'callUrl'?: string;
    /**
     * Time the call was started, in ISO 8601 format.
     */
    'startTime'?: string;
    /**
     * Time the call was answered, in ISO 8601 format.
     */
    'answerTime'?: string | null;
    /**
     * (optional) The tag specified on call creation. If no tag was specified or it was previously cleared, this field will not be present.
     */
    'tag'?: string | null;
    'referCallStatus'?: ReferCallStatusEnum;
    /**
     * (optional) The SIP response code returned for the REFER request itself (e.g. 202, 405, 603). Present when a SIP response was received for the REFER.
     */
    'referSipResponseCode'?: number;
    /**
     * (optional) The final SIP response code reported via NOTIFY (message/sipfrag body). Present only when the caller\'s endpoint sent a final NOTIFY (e.g. 200, 404, 486, 503). Not present on NOTIFY timeout or when the REFER was rejected before a subscription was established.
     */
    'notifySipResponseCode'?: number;
}



