/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The outcome of the REFER attempt. Possible values are success or failure.
 */

export const ReferCallStatus = {
    Success: 'success',
    Failure: 'failure'
} as const;

export type ReferCallStatus = typeof ReferCallStatus[keyof typeof ReferCallStatus];



