/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StatusCallbackMessage } from './status-callback-message';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusCallbackTypeEnum } from './status-callback-type-enum';

/**
 * Represents a status callback for an outbound MT SMS or MMS or RBM message.
 */
export interface StatusCallback {
    'time': string;
    /**
     * Represents the time at which the message was read, for `message-read` callbacks.
     */
    'eventTime'?: string;
    'type': StatusCallbackTypeEnum;
    /**
     * The destination phone number the message was sent to. For status callbacks, this the the Bandwidth user\'s client phone number.
     */
    'to': string;
    /**
     * A detailed description of the event described by the callback.
     */
    'description': string;
    'message': StatusCallbackMessage;
    /**
     * Optional error code, applicable only when type is `message-failed`.
     */
    'errorCode'?: number;
    /**
     * The name of the Authorized Message Provider (AMP) that handled this message.  In the US, this is the carrier that the message was sent to. This field is present only when this account feature has been enabled.
     */
    'carrierName'?: string;
}



