/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageDirectionEnum } from './message-direction-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiChannelMessageChannelEnum } from './multi-channel-message-channel-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { PriorityEnum } from './priority-enum';

/**
 * Message payload schema within a callback
 */
export interface StatusCallbackMessage {
    /**
     * A unique identifier of the message.
     */
    'id': string;
    /**
     * The Bandwidth phone number or alphanumeric identifier associated with the message.
     */
    'owner': string;
    /**
     * The ID of the Application your from number or senderId is associated with in the Bandwidth Phone Number Dashboard.
     */
    'applicationId': string;
    'time': string;
    /**
     * The number of segments the user\'s message is broken into before sending over carrier networks.
     */
    'segmentCount': number;
    'direction': MessageDirectionEnum;
    /**
     * The phone number recipients of the message.
     */
    'to': Set<string>;
    /**
     * The Bandwidth phone number or alphanumeric identifier the message was sent from.
     */
    'from': string;
    'text'?: string;
    /**
     * A custom string that will be included in callback events of the message. Max 1024 characters.
     */
    'tag'?: string;
    /**
     * Optional media, not applicable for sms
     */
    'media'?: Array<string>;
    'priority'?: PriorityEnum;
    'channel'?: MultiChannelMessageChannelEnum;
}



