/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TfvStatusEnum = {
    Verified: 'VERIFIED',
    Unverified: 'UNVERIFIED',
    Pending: 'PENDING'
} as const;

export type TfvStatusEnum = typeof TfvStatusEnum[keyof typeof TfvStatusEnum];



