/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The alignment of the thumbnail image in the card. Only applicable if the card using horizontal orientation.
 */

export const ThumbnailAlignmentEnum = {
    Left: 'LEFT',
    Right: 'RIGHT'
} as const;

export type ThumbnailAlignmentEnum = typeof ThumbnailAlignmentEnum[keyof typeof ThumbnailAlignmentEnum];



