/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Transcription
 */
export interface Transcription {
    /**
     * The transcribed text
     * @type {string}
     * @memberof Transcription
     */
    'text'?: string;
    /**
     * The confidence on the recognized content, ranging from `0.0` to `1.0` with `1.0` being the highest confidence.
     * @type {number}
     * @memberof Transcription
     */
    'confidence'?: number;
}

