/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallDirectionEnum } from './call-direction-enum';

/**
 * When processing a <Transfer> verb, this event is sent when a called party (B-leg) answers. The event is sent to the endpoint specified in the transferAnswerUrl attribute of the <PhoneNumber> tag that answered. BXML returned by this callback will be executed for the called party only. After all BXML has been executed, the called party will be bridged to the original call. Most BXML verbs are allowed in response to a transferAnswer event, but some are not allowed.
 */
export interface TransferAnswerCallback {
    /**
     * The event type, value can be one of the following: answer, bridgeComplete, bridgeTargetComplete, conferenceCreated, conferenceRedirect, conferenceMemberJoin, conferenceMemberExit, conferenceCompleted, conferenceRecordingAvailable, disconnect, dtmf, gather, initiate, machineDetectionComplete, recordingComplete, recordingAvailable, redirect, transcriptionAvailable, transferAnswer, transferComplete, transferDisconnect.
     */
    'eventType'?: string;
    /**
     * The approximate UTC date and time when the event was generated by the Bandwidth server, in ISO 8601 format. This may not be exactly the time of event execution.
     */
    'eventTime'?: string;
    /**
     * The user account associated with the call.
     */
    'accountId'?: string;
    /**
     * The id of the application associated with the call.
     */
    'applicationId'?: string;
    /**
     * The provided identifier of the caller. Must be a phone number in E.164 format (e.g. +15555555555).
     */
    'from'?: string;
    /**
     * The phone number that received the call, in E.164 format (e.g. +15555555555).
     */
    'to'?: string;
    'direction'?: CallDirectionEnum;
    /**
     * The call id associated with the event.
     */
    'callId'?: string;
    /**
     * The URL of the call associated with the event.
     */
    'callUrl'?: string;
    /**
     * (optional) If call queueing is enabled and this is an outbound call, time the call was queued, in ISO 8601 format.
     */
    'enqueuedTime'?: string | null;
    /**
     * Time the call was started, in ISO 8601 format.
     */
    'startTime'?: string;
    /**
     * Time the call was answered, in ISO 8601 format.
     */
    'answerTime'?: string | null;
    /**
     * (optional) The tag specified on call creation. If no tag was specified or it was previously cleared, this field will not be present.
     */
    'tag'?: string | null;
    /**
     * The phone number used as the from field of the B-leg call, in E.164 format (e.g. +15555555555).
     */
    'transferCallerId'?: string;
    /**
     * The phone number used as the to field of the B-leg call, in E.164 format (e.g. +15555555555).
     */
    'transferTo'?: string;
}



