/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateConferenceMember {
    /**
     * Whether or not this member is currently muted. Members who are muted are still able to hear other participants.  Updates this member\'s mute status. Has no effect if omitted.
     */
    'mute'?: boolean;
    /**
     * Whether or not this member is currently on hold. Members who are on hold are not able to hear or speak in the conference.  Updates this member\'s hold status. Has no effect if omitted.
     */
    'hold'?: boolean;
    /**
     * If this member had a value set for `callIdsToCoach` in its [Conference](/docs/voice/bxml/conference) verb or this list was added with a previous PUT request to modify the member, this is that list of calls.  Modifies the calls that this member is coaching. Has no effect if omitted. See the documentation for the [Conference](/docs/voice/bxml/conference) verb for more details about coaching.  Note that this will not add the matching calls to the conference; each call must individually execute a Conference verb to join.
     */
    'callIdsToCoach'?: Array<string> | null;
}

