/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { Contact } from './contact';
// May contain unused imports in some cases
// @ts-ignore
import type { OptInWorkflow } from './opt-in-workflow';

/**
 * 
 * @export
 * @interface VerificationUpdateRequest
 */
export interface VerificationUpdateRequest {
    /**
     * 
     * @type {Address}
     * @memberof VerificationUpdateRequest
     */
    'businessAddress': Address;
    /**
     * 
     * @type {Contact}
     * @memberof VerificationUpdateRequest
     */
    'businessContact': Contact;
    /**
     * Estimated monthly volume of messages from the toll-free number.
     * @type {number}
     * @memberof VerificationUpdateRequest
     */
    'messageVolume': number;
    /**
     * The category of the use case.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'useCase': string;
    /**
     * A general idea of the use case and customer.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'useCaseSummary': string;
    /**
     * Example of message content.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'productionMessageContent': string;
    /**
     * 
     * @type {OptInWorkflow}
     * @memberof VerificationUpdateRequest
     */
    'optInWorkflow': OptInWorkflow;
    /**
     * Any additional information.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'additionalInformation'?: string | null;
    /**
     * ISV name.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'isvReseller'?: string | null;
    /**
     * The Toll-Free Verification request privacy policy URL.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'privacyPolicyUrl'?: string;
    /**
     * The Toll-Free Verification request terms and conditions policy URL.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'termsAndConditionsUrl'?: string;
    /**
     * The company \'Doing Business As\'.
     * @type {string}
     * @memberof VerificationUpdateRequest
     */
    'businessDba'?: string;
}

