/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { BusinessEntityTypeEnum } from './business-entity-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { BusinessRegistrationTypeEnum } from './business-registration-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { Contact } from './contact';
// May contain unused imports in some cases
// @ts-ignore
import type { OptInWorkflow } from './opt-in-workflow';

export interface VerificationRequest {
    'businessAddress': Address;
    'businessContact': Contact;
    /**
     * Estimated monthly volume of messages from the toll-free number.
     */
    'messageVolume': number;
    'phoneNumbers': Array<string>;
    /**
     * The category of the use case.
     */
    'useCase': string;
    /**
     * A general idea of the use case and customer.
     */
    'useCaseSummary': string;
    /**
     * Example of message content.
     */
    'productionMessageContent': string;
    'optInWorkflow': OptInWorkflow;
    /**
     * Any additional information.
     */
    'additionalInformation'?: string | null;
    /**
     * ISV name.
     */
    'isvReseller'?: string | null;
    /**
     * The Toll-Free Verification request privacy policy URL.
     */
    'privacyPolicyUrl'?: string;
    /**
     * The Toll-Free Verification request terms and conditions policy URL.
     */
    'termsAndConditionsUrl'?: string;
    /**
     * The company \'Doing Business As\'.
     */
    'businessDba'?: string;
    /**
     * Government-issued business identifying number.  **Note:** If this field is provided, it is strongly recommended to also provide `businessRegistrationType` and `businessRegistrationIssuingCountry`. Submissions missing these fields have a high likelihood of rejection. 
     */
    'businessRegistrationNumber'?: string | null;
    'businessRegistrationType'?: BusinessRegistrationTypeEnum | null;
    /**
     * The country issuing the business registration in ISO-3166-1 alpha-3 format. Alpha-2 country codes are acceptable, but the application will convert them to alpha-3 when received, so alpha-3 is encouraged.  **Note:** If this field is omitted but `businessRegistrationType` is provided, the application will attempt to infer the country based on the registration type. However, if the application cannot confidently infer the country, the submission may be rejected. To ensure the highest likelihood of acceptance, it is recommended to provide both `businessRegistrationType` and `businessRegistrationIssuingCountry`.  | Registration Type     | Supported Countries                | |----------------------|------------------------------------| | EIN                  | USA                                | | CBN                  | CAN                                | | NEQ                  | CAN                                | | PROVINCIAL_NUMBER    | CAN                                | | CRN                  | GBR, HKG                           | | VAT                  | GBR, IRL, BRA, NLD                 | | ACN                  | AUS                                | | ABN                  | AUS                                | | BRN                  | HKG                                | | SIREN                | FRA                                | | SIRET                | FRA                                | | NZBN                 | NZL                                | | UST_IDNR             | DEU                                | | CIF                  | ESP                                | | NIF                  | ESP                                | | CNPJ                 | BRA                                | | UID                  | CHE                                | | OTHER                | Must Provide Country Code          |
     */
    'businessRegistrationIssuingCountry'?: string;
    'businessEntityType': BusinessEntityTypeEnum;
    /**
     * A message that gets sent to users requesting help.
     */
    'helpMessageResponse'?: string | null;
    /**
     * Indicates whether the content is age-gated.
     */
    'ageGatedContent'?: boolean;
    /**
     * The token provided by Campaign Verify to validate your political use case. Only required for 527 political organizations. If you are not a 527 political organization, this field should be omitted. Supplying an empty string will likely result in rejection.
     */
    'cvToken'?: string | null;
}



