/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerifyCodeRequest
 */
export interface VerifyCodeRequest {
    /**
     * The phone number to send the mfa code to.
     * @type {string}
     * @memberof VerifyCodeRequest
     */
    'to': string;
    /**
     * An optional field to denote what scope or action the mfa code is addressing.  If not supplied, defaults to \"2FA\".
     * @type {string}
     * @memberof VerifyCodeRequest
     */
    'scope'?: string;
    /**
     * The time period, in minutes, to validate the mfa code.  By setting this to 3 minutes, it will mean any code generated within the last 3 minutes are still valid.  The valid range for expiration time is between 0 and 15 minutes, exclusively and inclusively, respectively.
     * @type {number}
     * @memberof VerifyCodeRequest
     */
    'expirationTimeInMinutes': number;
    /**
     * The generated mfa code to check if valid.
     * @type {string}
     * @memberof VerifyCodeRequest
     */
    'code': string;
}

