/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TfvCallbackStatusEnum } from './tfv-callback-status-enum';

/**
 * 
 * @export
 * @interface VerificationWebhook
 */
export interface VerificationWebhook {
    /**
     * User\'s account ID.
     * @type {string}
     * @memberof VerificationWebhook
     */
    'accountId'?: string;
    /**
     * Toll-free telephone number in E.164 format.
     * @type {string}
     * @memberof VerificationWebhook
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {TfvCallbackStatusEnum}
     * @memberof VerificationWebhook
     */
    'status'?: TfvCallbackStatusEnum;
    /**
     * Unique identifier (UUID) generated by Bandwidth to assist in tracking the verification status of a toll-free number.
     * @type {string}
     * @memberof VerificationWebhook
     */
    'internalTicketNumber'?: string;
}



