/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VoiceApiError
 */
export interface VoiceApiError {
    /**
     * 
     * @type {string}
     * @memberof VoiceApiError
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoiceApiError
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoiceApiError
     */
    'id'?: string | null;
}

