/* tslint:disable */
/* eslint-disable */
/**
 * Bandwidth
 * Bandwidth\'s Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WebhookSubscriptionBasicAuthentication } from './webhook-subscription-basic-authentication';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookSubscriptionTypeEnum } from './webhook-subscription-type-enum';

/**
 * Information about a webhook that Bandwidth should send upon the completion of event customer has subscribed to.
 * @export
 * @interface WebhookSubscription
 */
export interface WebhookSubscription {
    /**
     * 
     * @type {string}
     * @memberof WebhookSubscription
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookSubscription
     */
    'accountId'?: string;
    /**
     * Callback URL to receive status updates from Bandwidth. When a webhook subscription is registered with Bandwidth under a given account ID, it will be used to send status updates for all requests submitted under that account ID.
     * @type {string}
     * @memberof WebhookSubscription
     */
    'callbackUrl': string | null;
    /**
     * 
     * @type {WebhookSubscriptionTypeEnum}
     * @memberof WebhookSubscription
     */
    'type'?: WebhookSubscriptionTypeEnum;
    /**
     * 
     * @type {WebhookSubscriptionBasicAuthentication}
     * @memberof WebhookSubscription
     */
    'basicAuthentication'?: WebhookSubscriptionBasicAuthentication;
    /**
     * 
     * @type {string}
     * @memberof WebhookSubscription
     */
    'createdDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookSubscription
     */
    'modifiedDate'?: string;
}



